name: build

on:
  push:
  pull_request:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-checkmate:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-checkmate

  run-phase:
    strategy:
      matrix:
        # Update this with `cargo checkmate list`
        phase: [check, format, clippy, build, test, doc, audit]
    needs: cache-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-checkmate
      - uses: actions/checkout@v3
      - run: cargo-checkmate run ${{ matrix.phase }}

  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-onedoc

    - name: Check README
      run: cargo onedoc --check
